import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import Head from 'next/head'
import Footer from './commons/footer'
import Header from './commons/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Notes App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  return (
    <>
   <html lang="en">
        <Head>
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css'/>
        </Head>
      <body className={inter.className}>
      <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css'/>
        <Header/>
        {children}
        <Footer/>
        </body>
      <Script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js'></Script>
      <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js'></Script>
    </html>
    </>
  )
}
